- hosts: all
  user: nil
  become: yes
  connection: ssh
  gather_facts: yes
  
  tasks:
    - name: install git
      action: yum pkg=git state=present
      
    - name: install docker
      action: yum pkg=docker state=present
