- hosts: all
  user: nil
  become: yes
  connection: ssh
  gather_facts: yes
  
  tasks:
    - name: install git
      action: yum pkg=git state=present
      
    - name: install java
      action: yum pkg=java:1.8 state=present
      
    - name: install docker
      action: yum pkg=docker state=present
      
    - name: service 
      action: sevice name=docker state=started
